[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/631854948",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4008#issuecomment-631854948",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4008",
        "id": 631854948,
        "node_id": "MDEyOklzc3VlQ29tbWVudDYzMTg1NDk0OA==",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-05-21T03:19:25Z",
        "updated_at": "2020-05-21T03:19:25Z",
        "author_association": "MEMBER",
        "body": "Is there a call stack from the error? It's strange it's in cudaMemcpy (vs memory allocation), so would need to know what it was trying to copy at the time.\r\n\r\nI don't have the same hardware so not sure I can repro. When you say 'starts failing' are you using the same InferenceSession for all the requests and changing provider and/or increasing batch size each time? ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/631854948/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/632392493",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4008#issuecomment-632392493",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4008",
        "id": 632392493,
        "node_id": "MDEyOklzc3VlQ29tbWVudDYzMjM5MjQ5Mw==",
        "user": {
            "login": "lifuhuang",
            "id": 3427331,
            "node_id": "MDQ6VXNlcjM0MjczMzE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3427331?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lifuhuang",
            "html_url": "https://github.com/lifuhuang",
            "followers_url": "https://api.github.com/users/lifuhuang/followers",
            "following_url": "https://api.github.com/users/lifuhuang/following{/other_user}",
            "gists_url": "https://api.github.com/users/lifuhuang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lifuhuang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lifuhuang/subscriptions",
            "organizations_url": "https://api.github.com/users/lifuhuang/orgs",
            "repos_url": "https://api.github.com/users/lifuhuang/repos",
            "events_url": "https://api.github.com/users/lifuhuang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lifuhuang/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-05-21T23:15:21Z",
        "updated_at": "2020-05-22T16:57:34Z",
        "author_association": "MEMBER",
        "body": "Thank you Scott for looking into the issue!\r\n\r\nI tried again today using a different hardware (both V100 and M60 GPU) and even different model (a similar BERT model from our partner team), the same issue seems to repro in all the cases. \r\n\r\nI couldn't seem to find and call stack in the error message and the issue happens regardless if I using the same InferenceSession for all requests and change provider and/or starting a new InferenceSession with a large batch size. Using a batch size 32 directly should repro the issue.\r\n\r\nPlease feel free to let me know if there is any extra information that I can provide.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/632392493/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/634516128",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4008#issuecomment-634516128",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4008",
        "id": 634516128,
        "node_id": "MDEyOklzc3VlQ29tbWVudDYzNDUxNjEyOA==",
        "user": {
            "login": "skottmckay",
            "id": 979079,
            "node_id": "MDQ6VXNlcjk3OTA3OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/979079?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/skottmckay",
            "html_url": "https://github.com/skottmckay",
            "followers_url": "https://api.github.com/users/skottmckay/followers",
            "following_url": "https://api.github.com/users/skottmckay/following{/other_user}",
            "gists_url": "https://api.github.com/users/skottmckay/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/skottmckay/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/skottmckay/subscriptions",
            "organizations_url": "https://api.github.com/users/skottmckay/orgs",
            "repos_url": "https://api.github.com/users/skottmckay/repos",
            "events_url": "https://api.github.com/users/skottmckay/events{/privacy}",
            "received_events_url": "https://api.github.com/users/skottmckay/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-05-27T08:38:33Z",
        "updated_at": "2020-05-27T08:38:33Z",
        "author_association": "MEMBER",
        "body": "So there are a lot of things interacting here. I boils down to an out of memory error from the arena that tries to allocate a large block for the whole run to use. It hits an edge case where it doesn't throw when it can't do the allocation, a nullptr is returned but that isn't checked for, and the nullptr gets stuffed in another stucture that we use when we need some memory for an Node. When we go to use that memory we get the nullptr (but assume it's a valid pointer to an offset within a large block) and that is passed to the cudaMemcpy as the destination address. In my testing where I saw an allocation failure instead of cudaMemcpy error it didn't hit this edge case - so it's actually the same root cause just with different error messages.\r\n\r\nThis happens on the second run as on the first one the arena doesn't know how large a block size to use so we allocate smaller blocks as we go along (if you run onnx_test_runner with '-v' you'll see output from BFCArena where these blocks are allocated). On the second run we go to allocate the large block, but we don't currently have a way to cleanup the smaller blocks from the first run which we're not going to use, leading to the out of memory error as now you essentially need 2x the memory (left over blocks from the first run and the single large block of the same total size for the second run). This is why TensorRT works with the batch size as it's not using this arena.\r\n\r\nAdditionally onnx_test_runner is reporting success for multiple runs even though only the first one is passing, which is why it's harder to notice the error when using that. \r\n\r\nShort term I'll see if we can handle the large block allocation failure better. Performance won't be totally optimal but it should still be able to use the smaller blocks from the first run so it shouldn't be too bad. There may be some other options but I'll need to test those out better and they may take a lot longer to validate and implement.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/634516128/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/663965155",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4008#issuecomment-663965155",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4008",
        "id": 663965155,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY2Mzk2NTE1NQ==",
        "user": {
            "login": "stale[bot]",
            "id": 26384082,
            "node_id": "MDM6Qm90MjYzODQwODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/1724?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stale%5Bbot%5D",
            "html_url": "https://github.com/apps/stale",
            "followers_url": "https://api.github.com/users/stale%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/stale%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/stale%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stale%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stale%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/stale%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/stale%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/stale%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stale%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "created_at": "2020-07-26T09:30:59Z",
        "updated_at": "2020-07-26T09:30:59Z",
        "author_association": "NONE",
        "body": "This issue has been automatically marked as stale due to inactivity and will be closed in 7 days if no further activity occurs. If further support is needed, please provide an update and/or more details.\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/663965155/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/667699832",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/4008#issuecomment-667699832",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/4008",
        "id": 667699832,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY2NzY5OTgzMg==",
        "user": {
            "login": "stale[bot]",
            "id": 26384082,
            "node_id": "MDM6Qm90MjYzODQwODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/1724?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stale%5Bbot%5D",
            "html_url": "https://github.com/apps/stale",
            "followers_url": "https://api.github.com/users/stale%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/stale%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/stale%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stale%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stale%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/stale%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/stale%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/stale%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stale%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "created_at": "2020-08-02T17:08:45Z",
        "updated_at": "2020-08-02T17:08:45Z",
        "author_association": "NONE",
        "body": "This issue has been automatically closed due to inactivity. Please reactivate if further support is needed.\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/667699832/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]