[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1149298285",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1149298285",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1149298285,
        "node_id": "IC_kwDOCVq1mM5EgOZt",
        "user": {
            "login": "natke",
            "id": 3302433,
            "node_id": "MDQ6VXNlcjMzMDI0MzM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3302433?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/natke",
            "html_url": "https://github.com/natke",
            "followers_url": "https://api.github.com/users/natke/followers",
            "following_url": "https://api.github.com/users/natke/following{/other_user}",
            "gists_url": "https://api.github.com/users/natke/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/natke/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/natke/subscriptions",
            "organizations_url": "https://api.github.com/users/natke/orgs",
            "repos_url": "https://api.github.com/users/natke/repos",
            "events_url": "https://api.github.com/users/natke/events{/privacy}",
            "received_events_url": "https://api.github.com/users/natke/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-08T00:09:55Z",
        "updated_at": "2022-06-08T00:09:55Z",
        "author_association": "MEMBER",
        "body": "@edelaye Are you able to answer this question for us?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1149298285/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1149830071",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1149830071",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1149830071,
        "node_id": "IC_kwDOCVq1mM5EiQO3",
        "user": {
            "login": "caleb-depotanalytics",
            "id": 104788759,
            "node_id": "U_kgDOBj7zFw",
            "avatar_url": "https://avatars.githubusercontent.com/u/104788759?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/caleb-depotanalytics",
            "html_url": "https://github.com/caleb-depotanalytics",
            "followers_url": "https://api.github.com/users/caleb-depotanalytics/followers",
            "following_url": "https://api.github.com/users/caleb-depotanalytics/following{/other_user}",
            "gists_url": "https://api.github.com/users/caleb-depotanalytics/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/caleb-depotanalytics/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/caleb-depotanalytics/subscriptions",
            "organizations_url": "https://api.github.com/users/caleb-depotanalytics/orgs",
            "repos_url": "https://api.github.com/users/caleb-depotanalytics/repos",
            "events_url": "https://api.github.com/users/caleb-depotanalytics/events{/privacy}",
            "received_events_url": "https://api.github.com/users/caleb-depotanalytics/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-08T12:08:11Z",
        "updated_at": "2022-06-08T12:09:01Z",
        "author_association": "NONE",
        "body": "@edelaye and @natke  - I was able to build onnxruntime on zcu102 using this script https://github.com/centennialsoftwaresolutions/vitis-ai-tutorial-helper-files/blob/main/install_onnxruntime_zcu102.sh\r\n\r\nBut as soon as I ran the vitisai-execution provider with this script (use any argument to make it run with vitisai instead of CPU) https://github.com/centennialsoftwaresolutions/vitis-ai-tutorial-helper-files/blob/main/compile_onnx_model.py. I got a Index out of bounds error.\r\n\r\nNot sure if I'm just doing something wrong or if there is a bug in onnxruntime with vitis ai.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1149830071/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150338701",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1150338701",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1150338701,
        "node_id": "IC_kwDOCVq1mM5EkMaN",
        "user": {
            "login": "elliott-xilinx",
            "id": 24442733,
            "node_id": "MDQ6VXNlcjI0NDQyNzMz",
            "avatar_url": "https://avatars.githubusercontent.com/u/24442733?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/elliott-xilinx",
            "html_url": "https://github.com/elliott-xilinx",
            "followers_url": "https://api.github.com/users/elliott-xilinx/followers",
            "following_url": "https://api.github.com/users/elliott-xilinx/following{/other_user}",
            "gists_url": "https://api.github.com/users/elliott-xilinx/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/elliott-xilinx/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/elliott-xilinx/subscriptions",
            "organizations_url": "https://api.github.com/users/elliott-xilinx/orgs",
            "repos_url": "https://api.github.com/users/elliott-xilinx/repos",
            "events_url": "https://api.github.com/users/elliott-xilinx/events{/privacy}",
            "received_events_url": "https://api.github.com/users/elliott-xilinx/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-08T19:51:41Z",
        "updated_at": "2022-06-08T19:51:41Z",
        "author_association": "CONTRIBUTOR",
        "body": "We have people using ONNXRuntime on our ZCU102/104 and also the VCK190 Versal boards.  I've asked one of my team members to follow up.  Are you getting a stack trace from the error that you can copy/paste?",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150338701/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150609358",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1150609358",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1150609358,
        "node_id": "IC_kwDOCVq1mM5ElOfO",
        "user": {
            "login": "caleb-depotanalytics",
            "id": 104788759,
            "node_id": "U_kgDOBj7zFw",
            "avatar_url": "https://avatars.githubusercontent.com/u/104788759?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/caleb-depotanalytics",
            "html_url": "https://github.com/caleb-depotanalytics",
            "followers_url": "https://api.github.com/users/caleb-depotanalytics/followers",
            "following_url": "https://api.github.com/users/caleb-depotanalytics/following{/other_user}",
            "gists_url": "https://api.github.com/users/caleb-depotanalytics/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/caleb-depotanalytics/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/caleb-depotanalytics/subscriptions",
            "organizations_url": "https://api.github.com/users/caleb-depotanalytics/orgs",
            "repos_url": "https://api.github.com/users/caleb-depotanalytics/repos",
            "events_url": "https://api.github.com/users/caleb-depotanalytics/events{/privacy}",
            "received_events_url": "https://api.github.com/users/caleb-depotanalytics/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-09T02:45:19Z",
        "updated_at": "2022-06-09T02:45:19Z",
        "author_association": "NONE",
        "body": "@elliott-xilinx - yeah here it is: \r\n\r\n_model.py ../yolov4_-1_3_384_384_dynamic.onnx fpgaer-files# python3 compile_onnx_\r\n2022-06-08 22:43:37.854854490 [E:onnxruntime:, inference_session.cc:1458 operator()] Exception during initialization: IndexError: list index out of range\r\n\r\nAt:\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__\r\n  compile_onnx_model.py(21): execute_with_fpga\r\n  compile_onnx_model.py(28): <module>\r\n\r\nTraceback (most recent call last):\r\n  File \"compile_onnx_model.py\", line 28, in <module>\r\n    execute_with_fpga(sys.argv[1])\r\n  File \"compile_onnx_model.py\", line 21, in execute_with_fpga\r\n    session = onnxruntime.InferenceSession(model_name, None, [\"VitisAIExecutionProvider\"], [vitis_ai_provider_options])\r\n  File \"/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 324, in __init__\r\n    self._create_inference_session(providers, provider_options, disabled_optimizers)\r\n  File \"/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 369, in _create_inference_sessio\r\nn\r\n    sess.initialize_session(providers, provider_options, disabled_optimizers)\r\nonnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initializ\r\nation: IndexError: list index out of range\r\n\r\nAt:\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onn\r\nx_2_xlayer\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__\r\n  compile_onnx_model.py(21): execute_with_fpga\r\n  compile_onnx_model.py(28): <module>\r\n\r\n\r\nAnd that is coming from this inside the script:\r\ndef execute_with_fpga(model_name):\r\n    target='DPUCADX8G'\r\n    vitis_ai_provider_options = {'target': target, 'export_runtime_module': 'vitis_ai_dpu.rtmod'}\r\n    session = onnxruntime.InferenceSession(model_name, None, [\"VitisAIExecutionProvider\"], [vitis_ai_provider_options])",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150609358/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150615230",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1150615230",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1150615230,
        "node_id": "IC_kwDOCVq1mM5ElP6-",
        "user": {
            "login": "elliott-xilinx",
            "id": 24442733,
            "node_id": "MDQ6VXNlcjI0NDQyNzMz",
            "avatar_url": "https://avatars.githubusercontent.com/u/24442733?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/elliott-xilinx",
            "html_url": "https://github.com/elliott-xilinx",
            "followers_url": "https://api.github.com/users/elliott-xilinx/followers",
            "following_url": "https://api.github.com/users/elliott-xilinx/following{/other_user}",
            "gists_url": "https://api.github.com/users/elliott-xilinx/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/elliott-xilinx/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/elliott-xilinx/subscriptions",
            "organizations_url": "https://api.github.com/users/elliott-xilinx/orgs",
            "repos_url": "https://api.github.com/users/elliott-xilinx/repos",
            "events_url": "https://api.github.com/users/elliott-xilinx/events{/privacy}",
            "received_events_url": "https://api.github.com/users/elliott-xilinx/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-09T02:59:39Z",
        "updated_at": "2022-06-09T02:59:39Z",
        "author_association": "CONTRIBUTOR",
        "body": "First thing I see is the target you're passing in is an Alveo DPU, (DPUCADX8G).  The Zync DPUs should typically be DPUCZDX8G.  Change that target on all your scripts.  Since we compile first on x86, you should make sure the first run on x86 also has DPUCZDX8G.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150615230/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150617974",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1150617974",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1150617974,
        "node_id": "IC_kwDOCVq1mM5ElQl2",
        "user": {
            "login": "caleb-depotanalytics",
            "id": 104788759,
            "node_id": "U_kgDOBj7zFw",
            "avatar_url": "https://avatars.githubusercontent.com/u/104788759?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/caleb-depotanalytics",
            "html_url": "https://github.com/caleb-depotanalytics",
            "followers_url": "https://api.github.com/users/caleb-depotanalytics/followers",
            "following_url": "https://api.github.com/users/caleb-depotanalytics/following{/other_user}",
            "gists_url": "https://api.github.com/users/caleb-depotanalytics/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/caleb-depotanalytics/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/caleb-depotanalytics/subscriptions",
            "organizations_url": "https://api.github.com/users/caleb-depotanalytics/orgs",
            "repos_url": "https://api.github.com/users/caleb-depotanalytics/repos",
            "events_url": "https://api.github.com/users/caleb-depotanalytics/events{/privacy}",
            "received_events_url": "https://api.github.com/users/caleb-depotanalytics/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-09T03:05:27Z",
        "updated_at": "2022-06-09T03:05:27Z",
        "author_association": "NONE",
        "body": "Yeah, I had messed around with that variable quite a bit since I was getting the error, but it's the same log with DPUCZDX8G\r\n\r\nroot@xilinx-zcu102-2021_2:~/vitis-ai-tutorial-helper-files# python3 compile_onnx_model.py ../yolov4_-1_3_384_384_dynamic.onnx fpga\r\n2022-06-08 23:03:21.272684680 [E:onnxruntime:, inference_session.cc:1458 operator()] Exception during initialization: IndexError: list index out of range\r\n\r\nAt:\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__\r\n  compile_onnx_model.py(21): execute_with_fpga\r\n  compile_onnx_model.py(28): <module>\r\n\r\nTraceback (most recent call last):\r\n  File \"compile_onnx_model.py\", line 28, in <module>\r\n    execute_with_fpga(sys.argv[1])\r\n  File \"compile_onnx_model.py\", line 21, in execute_with_fpga\r\n    session = onnxruntime.InferenceSession(model_name, None, [\"VitisAIExecutionProvider\"], [vitis_ai_provider_options])\r\n  File \"/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 324, in __init__\r\n    self._create_inference_session(providers, provider_options, disabled_optimizers)\r\n  File \"/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 369, in _create_inference_session\r\n    sess.initialize_session(providers, provider_options, disabled_optimizers)\r\nonnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: IndexError: list index out of range\r\n\r\nAt:\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func\r\n  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session\r\n  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__\r\n  compile_onnx_model.py(21): execute_with_fpga\r\n  compile_onnx_model.py(28): <module>\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1150617974/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1151232566",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1151232566",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1151232566,
        "node_id": "IC_kwDOCVq1mM5Enmo2",
        "user": {
            "login": "caleb-depotanalytics",
            "id": 104788759,
            "node_id": "U_kgDOBj7zFw",
            "avatar_url": "https://avatars.githubusercontent.com/u/104788759?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/caleb-depotanalytics",
            "html_url": "https://github.com/caleb-depotanalytics",
            "followers_url": "https://api.github.com/users/caleb-depotanalytics/followers",
            "following_url": "https://api.github.com/users/caleb-depotanalytics/following{/other_user}",
            "gists_url": "https://api.github.com/users/caleb-depotanalytics/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/caleb-depotanalytics/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/caleb-depotanalytics/subscriptions",
            "organizations_url": "https://api.github.com/users/caleb-depotanalytics/orgs",
            "repos_url": "https://api.github.com/users/caleb-depotanalytics/repos",
            "events_url": "https://api.github.com/users/caleb-depotanalytics/events{/privacy}",
            "received_events_url": "https://api.github.com/users/caleb-depotanalytics/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-06-09T14:59:17Z",
        "updated_at": "2022-06-09T14:59:17Z",
        "author_association": "NONE",
        "body": "It's also worth noting that I translated this into an onnx model from tensorflow. Not sure if that's relevant here.",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1151232566/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1186018828",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/11505#issuecomment-1186018828",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/11505",
        "id": 1186018828,
        "node_id": "IC_kwDOCVq1mM5GsTYM",
        "user": {
            "login": "musheikh2",
            "id": 108955668,
            "node_id": "U_kgDOBn6IFA",
            "avatar_url": "https://avatars.githubusercontent.com/u/108955668?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/musheikh2",
            "html_url": "https://github.com/musheikh2",
            "followers_url": "https://api.github.com/users/musheikh2/followers",
            "following_url": "https://api.github.com/users/musheikh2/following{/other_user}",
            "gists_url": "https://api.github.com/users/musheikh2/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/musheikh2/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/musheikh2/subscriptions",
            "organizations_url": "https://api.github.com/users/musheikh2/orgs",
            "repos_url": "https://api.github.com/users/musheikh2/repos",
            "events_url": "https://api.github.com/users/musheikh2/events{/privacy}",
            "received_events_url": "https://api.github.com/users/musheikh2/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-07-15T23:21:50Z",
        "updated_at": "2022-07-15T23:21:50Z",
        "author_association": "NONE",
        "body": "Getting exactly the same issue with every onnx model that I use except the Resnet 18 from the example here:\r\n\r\nhttps://github.com/Xilinx/Vitis-AI/tree/master/third_party/onnxruntime\r\n\r\nCannot figure out what is special about Resnet 18 that the session runs fine. I haven't been able to find another model that runs fine.\r\n\r\nHave you been able to figure out a solution @caleb-depotanalytics ? ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/1186018828/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]