[
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/517478273",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/1542#issuecomment-517478273",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/1542",
        "id": 517478273,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxNzQ3ODI3Mw==",
        "user": {
            "login": "snnn",
            "id": 856316,
            "node_id": "MDQ6VXNlcjg1NjMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/856316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snnn",
            "html_url": "https://github.com/snnn",
            "followers_url": "https://api.github.com/users/snnn/followers",
            "following_url": "https://api.github.com/users/snnn/following{/other_user}",
            "gists_url": "https://api.github.com/users/snnn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snnn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snnn/subscriptions",
            "organizations_url": "https://api.github.com/users/snnn/orgs",
            "repos_url": "https://api.github.com/users/snnn/repos",
            "events_url": "https://api.github.com/users/snnn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snnn/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-01T22:18:17Z",
        "updated_at": "2019-08-01T22:18:17Z",
        "author_association": "MEMBER",
        "body": "Please report this bug to Pytorch. The model itself is incorrect. \r\nThere is an Mul node, which has two inputs, one is \"tensor(int64)\", another is \"tensor(float)\".  They should be the same type.  I can't tell you it is which node, because the node name is empty.  It would be better if the Pytorch can generate a unique  name for each node. \r\n\r\n\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/517478273/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/518102430",
        "html_url": "https://github.com/microsoft/onnxruntime/issues/1542#issuecomment-518102430",
        "issue_url": "https://api.github.com/repos/microsoft/onnxruntime/issues/1542",
        "id": 518102430,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUxODEwMjQzMA==",
        "user": {
            "login": "ajaysg-zz",
            "id": 22977639,
            "node_id": "MDQ6VXNlcjIyOTc3NjM5",
            "avatar_url": "https://avatars.githubusercontent.com/u/22977639?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ajaysg-zz",
            "html_url": "https://github.com/ajaysg-zz",
            "followers_url": "https://api.github.com/users/ajaysg-zz/followers",
            "following_url": "https://api.github.com/users/ajaysg-zz/following{/other_user}",
            "gists_url": "https://api.github.com/users/ajaysg-zz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ajaysg-zz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ajaysg-zz/subscriptions",
            "organizations_url": "https://api.github.com/users/ajaysg-zz/orgs",
            "repos_url": "https://api.github.com/users/ajaysg-zz/repos",
            "events_url": "https://api.github.com/users/ajaysg-zz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ajaysg-zz/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-05T06:25:08Z",
        "updated_at": "2019-08-05T11:00:18Z",
        "author_association": "NONE",
        "body": "@snnn its a bug with onnxrt. before exporting the pytorch model to onnx, i have converted the model to float using the command\r\n\r\n`model1=model.float()`\r\n\r\nnow all the tensors in the model1 is float.\r\n\r\n`mel_extra=torch.tensor(np.full((1,80,222),-10.0)).float()`\r\n`dummy_input=torch.autograd.Variable(mel_extra).cuda().float()`\r\n`audio = torch.tensor(np.full((1,222), -0.5)).float()`\r\n`audio_input = torch.autograd.Variable(audio).cuda().float()`\r\n`torch.onnx.export(model1, ((dummy_input, audio_input),), \"./waveglow.onnx\")`\r\n\r\nThen i passed the float tensors as mentioned above and traced the onnx graph. Onnx export was successful. When i try to use it in onnxrt by starting the session \r\n\r\n`sess = rt.InferenceSession(\"../waveglow.onnx\")`\r\n\r\nit throws the error referenced in the issue. ",
        "reactions": {
            "url": "https://api.github.com/repos/microsoft/onnxruntime/issues/comments/518102430/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]